name: Status Check

on:
  schedule:
    - cron: "*/1 * * * *"  # Каждые 10 минут
  workflow_dispatch: True

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run status check
        run: python ping_check.py

      - name: Commit and push status
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "actions@github.com"
          git add status.json
          git commit -m "Update status [skip ci]" || echo "No changes to commit"
          git push
